import type { ShadowMapMode } from './shadowMapModes'

export const siteVisualConfig = {
  background: 'paper',
  font: 'geist',
  shadowMapMode: 'mixed' satisfies ShadowMapMode,
  shadowSettings: {
    blindStrength: 0.12,
    canopyStrength: 1,
    canopyStyle: 'oak',
    contrast: 0.9,
    crispness: 3,
    density: 1,
    depthMix: 0.75,
    layerSpread: 1.15,
    opacity: 0.19,
    resolution: 1,
    sampleCount: 100,
    samplerX: 0.52,
    samplerY: 0.5,
    scale: 1.4,
    speed: 0.55,
    sunAngle: 2.95,
    wind: 1.5,
  },
  textureSettings: {
    opacity: 0.17,
    scale: 200,
  },
  typeSettings: {
    lineHeight: 1.55,
    size: 1.02,
    tracking: 0,
    weight: 300,
    width: 35,
  },
  responsivePresets: {
    mobilePortrait: {
      maxAspect: 1.25,
      shadowSettings: {
        blindStrength: 0.12,
        canopyStrength: 1,
        canopyStyle: 'oak',
        contrast: 0.95,
        crispness: 3,
        density: 1.45,
        depthMix: 0.8,
        layerSpread: 1.95,
        opacity: 0.2,
        resolution: 1,
        sampleCount: 100,
        samplerX: 0.52,
        samplerY: 0.5,
        scale: 1.35,
        speed: 1.1,
        sunAngle: 2.95,
        wind: 1.5,
      },
      textureSettings: {
        opacity: 0.17,
        scale: 200,
      },
      typeSettings: {
        lineHeight: 1.55,
        size: 1.02,
        tracking: 0,
        weight: 300,
        width: 35,
      },
    },
  },
} as const
